### PR TITLE
Added NLTM authentification for sending items down the elasticsearch …

### PR DESCRIPTION
**Pull request by jsgervais**
Added NLTM authentification for sending items down the scrapy-elasticsearch pipeline.  
Only needed to override the default Transport class in elasticsearch client.

Add those variables in your crawler settings.py file
ELASTICSEARCH_AUTH = 'NTLM'  # NTLM
ELASTICSEARCH_USERNAME = 'Domain\user'
ELASTICSEARCH_PASSWORD = 'password'

### CODE REVIEW

**Comment by jayzeng** [comment]
@jsgervais thanks for your PR, can you also update the README to reflect the new settings?

**Comment by jayzeng** [comment]
@jsgervais LGTM, don't really have a way to test your change. I assume you have battle tested your changes somewhere?

**Comment by jsgervais** [comment]
The change in the pipeline shouldn't break any existing crawlers since they won't use the new configs variable in their settings;

Updating to 0.8.0 adds a new requirement for the requests lib (fairly common) and requests_ntlm lib.

**Comment by jayzeng** [comment]
@jsgervais just merged another PR, mind resolving the merge conflict?

**Comment by jsgervais** [comment]
Not sure how I can update my fork on github so I can try to merge changes locally and resolve conflicts.    And I cannot do it on your repository since I only have read access ;)

I think the only real conflict is the readme.rst fil as both PR updated version number

**Comment by jayzeng** [comment]
You just need to resolve the merge conflict locally, push to your forked remote, github will pick it up and show it here automatically

**Comment by jsgervais** [comment]
got it.  ;)

**Comment by jayzeng** [comment]
thanks @jsgervais :)

**Pull request merged**
