### PR TITLE
module name change :bug: uniq_key

### PR DESCRIPTION
**Pull request by songzhiyong**

### CODE REVIEW

**Comment by jayzeng** [comment]
@songzhiyong what you want is to set ELASTICSEARCH_UNIQ_KEY = "your unique field", and I am not sure why you want to the module name, mind elaborate a bit?

**Comment by jayzeng** [comment]
also it has merge conflict

**Comment by songzhiyong** [comment]
sorry, I just realised that my fork was long time ago, and the undefined uniq_key bug has already fixed

**Comment by jayzeng** [comment]
Ah, no worries, thanks for the PR :)

**Pull request merged**
